---
- set_fact:
    swapfile_location: /mnt/local/swapfile
  when: volumes.stdout_lines

- set_fact:
    swapfile_location: /mnt/swapfile
  when: not volumes.stdout_lines

- set_fact:
    swapfile_size: "{{ ansible_memtotal_mb }}MB"
  when: not swapfile_size

- name: write swapfile
  command: |
    {% if swapfile_use_dd %}
    dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
    {% else %}
    fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
    {% endif %}
  register: write_swapfile

- name: set swapfile permissions
  file: path={{ swapfile_location }} mode=0600

- name: create swapfile
  command: mkswap {{ swapfile_location }}
  register: create_swapfile
  when: write_swapfile.changed

- name: enable swapfile
  command: swapon {{ swapfile_location }}
  when: create_swapfile.changed

- name: add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present

- name: configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: reload sysctl
  when: swapfile_swappiness != false

- name: configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  notify: reload sysctl
  when: swapfile_vfs_cache_pressure != false
