---
- name: define swapfile as /mnt/local/swapfile
  set_fact:
    swapfile_location: /mnt/local/swapfile
  when: volumes.stdout_lines

- name: define swapfile as /mnt/swapfile
  set_fact:
    swapfile_location: /mnt/swapfile
  when: not volumes.stdout_lines

- name: define swapfile size
  set_fact:
    swapfile_size: "{{ ansible_memtotal_mb }}MB"
  when: not swapfile_size

- name: write swapfile
  command: |
    {% if swapfile_use_dd %}
    dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
    {% else %}
    fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
    {% endif %}
  register: write_swapfile

- name: set swapfile permissions
  file: path={{ swapfile_location }} mode=0600

- name: create swapfile
  command: mkswap {{ swapfile_location }}
  register: create_swapfile
  when: write_swapfile.changed

- name: enable swapfile
  command: swapon {{ swapfile_location }}
  when: create_swapfile.changed

- name: add swapfile to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: "{{ swapfile_location }}   none    swap    sw    0   0"
    state: present

- name: configure vm.swappiness
  sysctl:
    state: present
    reload: yes
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
  when: swapfile_swappiness != false

- name: configure vm.vfs_cache_pressure
  sysctl:
    state: present
    reload: yes
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
  when: swapfile_vfs_cache_pressure != false
